export class Anexo4 {
  id?:Number;
  fechaRespuesta?:Date;
  estudianteTitulo?:String;
  nombreEstudiante?:String;
  siglasCarrera?:String;
  nombreProyecto?:String;
  nombreDirector?:String;
  nombreRepresentante?:String;
  numeroHoras?:String;
  nombreResponsable?:String;
  fechaRecepcionEst?:Date;
  idProyectoPPP?:Number;
  documento?:String;
  cedulaEstudiante?:String;
  cedulaDirector?:String;
  cedulaRepresentante?:String;
  cedulaResponsable?:String;
  num_proceso?:Number;
}
